### ISSUE TITLE
1.0.0 Release checklist

### ISSUE THREAD

**Issue by avojak** [avojak/iridium#64]
Checklist of items to verify prior to 1.0.0 readiness:

- [x] Ensure only required debugging/print statements to console and log (still print noisier output in dev mode for debugging)
- [x] Update debian/changelog
- [x] Set description in debian/control
- [x] Set release version (meson.build, debian/changelog)
- [x] Set release date (debian/changelog, appdata.xml)
- [x] Use updated screenshots (data/appdata.xml)
- [x] Set price
- [x] Check POTFILES up-to-date

**Comment by avojak** [comment]
I think (at least) the preference dialog needs to be non-modal
